dist: xenial
cache:
  directories:
    - download
language: python
env:
  - VERSION=2.9.2 MD5=82db6a62febd8c2976d75b8bd5513315
  - VERSION=3.0.3 MD5=88a615d8a2e883cd00c211b45ed33977
python:
  # https://docs.python.org/devguide/#status-of-python-branches
  - "2.7"
  - "3.6"
  - "3.7"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"
before_install:
  - ./install-hdfs.sh
  - pip install codecov
install:
  - pip install -e .
  - pip install --upgrade -r dev_requirements.txt
script: PATH=hadoop/bin:$PATH PYTHONHASHSEED=random pytest
after_success: codecov
